### ISSUE TITLE
首先感谢您做的项目，然后想说下xmind的问题

### ISSUE THREAD

**Issue by TanGuiping** [SSHeRun/CS-Xmind-Note#10]
几乎所有的xmind打不开，请问是因为版本问题吗，我用的是xmind 8 pro

**Comment by Chandler-Lu** [comment]
作者用zen做的

**Comment by TanGuiping** [comment]
> 作者用zen做的

谢谢，解决了

**Comment by MrXsc** [comment]
提一句，XMind 格式本质是 json，所以您有很多方法去解决未来关于xmind的格式类似问题或扩展。
