### ISSUE TITLE
操作系统第四章图片

### ISSUE THREAD

**Issue by Steventxy** [SSHeRun/CS-Xmind-Note#14]
![第四章 存储器管理](https://user-images.githubusercontent.com/50989379/80680815-0d6a2400-8af2-11ea-9673-978fa30a06bf.png)

**Comment by swaggy-w** [comment]
为什么我所有图片都下载不了 也点开不了

**Comment by Steventxy** [comment]
网的问题，翻个墙就行了

**Comment by swaggy-w** [comment]
okk 谢谢XD
