### ISSUE TITLE
计算机网络 物理层部分少了虚电路

### ISSUE THREAD

**Issue by 1104662797** [SSHeRun/CS-Xmind-Note#4]

**Comment by SSHeRun** [comment]
虚电路不是网络层的吗？

**Comment by 1104662797** [comment]
那可能是我看的是王道的书，他归类到了物理层我就以为到了物理层，不好意思是我的错

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 圣三一 <notifications@github.com&gt;
发送时间: 2019年8月29日 23:28
收件人: SSHeRun/CS-Xmind-Note <CS-Xmind-Note@noreply.github.com&gt;
抄送: 1104662797 <1104662797@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[SSHeRun/CS-Xmind-Note] 计算机网络 物理层部分少了虚电路 (#4)




虚电路不是网络层的吗？
